server:
  port: 8084

spring:
  cloud:
    function:
      definition: consumeForValidate;requestOrdering
    stream:
      bindings:
        consumeForValidate-in-0:
          content-type: application/json
          destination: entry
          group: validator

        requestOrdering-out-0:
          destination: ordering
