server:
  port: 8083

spring:
  cloud:
    function:
      definition: consumeForValidate;
    stream:
      bindings:
        consumeForValidate-in-0:
          content-type: application/json
          destination: entry
          group: validator

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false

#logging:
#  level:
#    org.hibernate.SQL: debug