#spring:
#  cloud:
#    stream:
#      bindings:
#        entryProducer-out-0:
#          destination: entry
#          content-type: application/json

spring:
  data:
    mongodb:
      database: sequence
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      uri: mongodb://127.0.0.1:27017/test?maxPoolSize=100

# thread
  task:
    execution:
      pool:
        core-size: 100