#spring:
#  cloud:
#    stream:
#      bindings:
#        entryProducer-out-0:
#          destination: entry
#          content-type: application/json

spring:
  task:
    execution:
      pool:
        core-size: 100